apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-app-1
  description: 'My Cool App'
  annotations:
    github.com/project-slug: zenardi-org/react-app-1
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "title == 'Kubernetes / Compute Resources / Workload'"
    grafana/overview-dashboard: "http://grafana.local/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&from=now-1h&to=now&timezone=utc&var-datasource=default&var-cluster=&var-namespace=react-app-1&var-type=$__all&var-workload=$__all&refresh=10s"
  links:
    - url: http://react-app-1.local
      title: react-app-1 Link
      icon: dashboard
      type: admin-dashboard
  tags:
    - react
    - typescript
spec:
  type: website
  owner: group:default/development

  lifecycle: experimental


